---
deployment:
  tasks:
    - export DEPLOYPATH=$HOME/public_html/
    - /bin/mkdir -p "$DEPLOYPATH"
    - /bin/mkdir -p "$DEPLOYPATH/cache"
    - /bin/cp index.html "$DEPLOYPATH"
    - /bin/cp .htaccess "$DEPLOYPATH"
    - /bin/cp robots.txt "$DEPLOYPATH"
    - /bin/cp -R api "$DEPLOYPATH"
    - /bin/cp -R assets "$DEPLOYPATH"
    - /bin/cp -R config "$DEPLOYPATH"
    - /bin/cp -R content "$DEPLOYPATH"
    - /bin/chmod 755 "$DEPLOYPATH"
    - /bin/chmod 775 "$DEPLOYPATH/cache"
